name: tgram
description: A Wrapper around tg.
version: 0.0.1
repository: https://github.com/DeekshithSH/tgram

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # tg: ^0.0.7
  tg:
    # path: ../../packages/tg
    git:
      url: https://github.com/DeekshithSH/tg
      ref: patch-3
  t: any
  socks5_proxy: ^1.0.4
  synchronized: ^3.3.0+3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
